export const events = [
  {
    image: "/images/event1.png",
    slug: "nextjs-conf-2026",
    location: "San Francisco, CA",
    date: "October 24, 2026",
    time: "09:00 AM PST",
    title: "Next.js Conf 2026",
  },
  {
    image: "/images/event2.png",
    slug: "react-summit-amsterdam",
    location: "Amsterdam, Netherlands",
    date: "June 14, 2026",
    time: "10:00 AM CET",
    title: "React Summit Europe",
  },
  {
    image: "/images/event3.png",
    slug: "aws-reinvent-2026",
    location: "Las Vegas, NV",
    date: "November 30, 2026",
    time: "08:30 AM PST",
    title: "AWS re:Invent",
  },
  {
    image: "/images/event4.png",
    slug: "google-io-26",
    location: "Mountain View, CA",
    date: "May 12, 2026",
    time: "10:00 AM PST",
    title: "Google I/O 2026",
  },
  {
    image: "/images/event5.png",
    slug: "github-universe",
    location: "San Francisco, CA",
    date: "November 10, 2026",
    time: "09:30 AM PST",
    title: "GitHub Universe",
  },
  {
    image: "/images/event6.png",
    slug: "kubecon-na-2026",
    location: "Chicago, IL",
    date: "November 6, 2026",
    time: "09:00 AM CST",
    title: "KubeCon + CloudNativeCon",
  },
];
